package gzrd.wsclient.menu.wsinterface;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:37:26.501+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "MenuWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface MenuWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMenusByUserIdAndAppCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetMenusByUserIdAndAppCode")
    @WebMethod
    @ResponseWrapper(localName = "getMenusByUserIdAndAppCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetMenusByUserIdAndAppCodeResponse")
    public java.util.List<Menu> getMenusByUserIdAndAppCode(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllMenusByUserIdAndAppCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetAllMenusByUserIdAndAppCode")
    @WebMethod
    @ResponseWrapper(localName = "getAllMenusByUserIdAndAppCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetAllMenusByUserIdAndAppCodeResponse")
    public java.util.List<Menu> getAllMenusByUserIdAndAppCode(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSetupMenusByUserIdAndAppCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetSetupMenusByUserIdAndAppCode")
    @WebMethod
    @ResponseWrapper(localName = "getSetupMenusByUserIdAndAppCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.menu.wsinterface.GetSetupMenusByUserIdAndAppCodeResponse")
    public java.util.List<Menu> getSetupMenusByUserIdAndAppCode(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );
}
