package gzrd.wsclient.menu.wsinterface;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:37:26.611+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "MenuWebService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/MenuWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class MenuWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "MenuWebService");
    public final static QName MenuWebServicePort = new QName("http://hugeinfo.com.cn", "MenuWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/MenuWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(MenuWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/MenuWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public MenuWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MenuWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns MenuWebService
     */
    @WebEndpoint(name = "MenuWebServicePort")
    public MenuWebService getMenuWebServicePort() {
        return super.getPort(MenuWebServicePort, MenuWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MenuWebService
     */
    @WebEndpoint(name = "MenuWebServicePort")
    public MenuWebService getMenuWebServicePort(WebServiceFeature... features) {
        return super.getPort(MenuWebServicePort, MenuWebService.class, features);
    }

}
