package gzrd.wsclient.post;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:44:46.094+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "PositionWebService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/PositionWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class PositionWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "PositionWebService");
    public final static QName PositionWebServicePort = new QName("http://hugeinfo.com.cn", "PositionWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/PositionWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PositionWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/PositionWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PositionWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PositionWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PositionWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns PositionWebService
     */
    @WebEndpoint(name = "PositionWebServicePort")
    public PositionWebService getPositionWebServicePort() {
        return super.getPort(PositionWebServicePort, PositionWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PositionWebService
     */
    @WebEndpoint(name = "PositionWebServicePort")
    public PositionWebService getPositionWebServicePort(WebServiceFeature... features) {
        return super.getPort(PositionWebServicePort, PositionWebService.class, features);
    }

}
