package gzrd.wsclient.post;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:44:46.047+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "PositionWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface PositionWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getParentPoss", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetParentPoss")
    @WebMethod
    @ResponseWrapper(localName = "getParentPossResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetParentPossResponse")
    public java.util.List<User> getParentPoss(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMainPosByLoginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetMainPosByLoginName")
    @WebMethod
    @ResponseWrapper(localName = "getMainPosByLoginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetMainPosByLoginNameResponse")
    public String getMainPosByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPositionChangeInfos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionChangeInfos")
    @WebMethod
    @ResponseWrapper(localName = "getPositionChangeInfosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionChangeInfosResponse")
    public java.util.List<UpPositionChangeForm> getPositionChangeInfos(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPositionById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionById")
    @WebMethod
    @ResponseWrapper(localName = "getPositionByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionByIdResponse")
    public Position getPositionById(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChildPoss", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetChildPoss")
    @WebMethod
    @ResponseWrapper(localName = "getChildPossResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetChildPossResponse")
    public java.util.List<User> getChildPoss(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPosIdsByRoleId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPosIdsByRoleId")
    @WebMethod
    @ResponseWrapper(localName = "getPosIdsByRoleIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPosIdsByRoleIdResponse")
    public java.util.List<Long> getPosIdsByRoleId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSonPoss", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetSonPoss")
    @WebMethod
    @ResponseWrapper(localName = "getSonPossResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetSonPossResponse")
    public java.util.List<User> getSonPoss(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPossByDeptId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByDeptId")
    @WebMethod
    @ResponseWrapper(localName = "getPossByDeptIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByDeptIdResponse")
    public java.util.List<Position> getPossByDeptId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFirstPosByOrgId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetFirstPosByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getFirstPosByOrgIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetFirstPosByOrgIdResponse")
    public Position getFirstPosByOrgId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFirstPosByDeptId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetFirstPosByDeptId")
    @WebMethod
    @ResponseWrapper(localName = "getFirstPosByDeptIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetFirstPosByDeptIdResponse")
    public Position getFirstPosByDeptId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPeigangChangeInfos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPeigangChangeInfos")
    @WebMethod
    @ResponseWrapper(localName = "getPeigangChangeInfosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPeigangChangeInfosResponse")
    public java.util.List<UpUserPosChangeForm> getPeigangChangeInfos(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPossByOrgId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getPossByOrgIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByOrgIdResponse")
    public java.util.List<Position> getPossByOrgId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMainPosFormByLoginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetMainPosFormByLoginName")
    @WebMethod
    @ResponseWrapper(localName = "getMainPosFormByLoginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetMainPosFormByLoginNameResponse")
    public UpPositionForm getMainPosFormByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPossByUserId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByUserId")
    @WebMethod
    @ResponseWrapper(localName = "getPossByUserIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPossByUserIdResponse")
    public java.util.List<Position> getPossByUserId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getPositionsByRole", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionsByRole")
    @WebMethod
    @ResponseWrapper(localName = "getPositionsByRoleResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.post.GetPositionsByRoleResponse")
    public java.util.List<Position> getPositionsByRole(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );
}
