package gzrd.wsclient.navigation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:40:32.292+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "NavigationService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/NavigationWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class NavigationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "NavigationService");
    public final static QName NavigationServicePort = new QName("http://hugeinfo.com.cn", "NavigationServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/NavigationWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(NavigationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/NavigationWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public NavigationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public NavigationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public NavigationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns NavigationWebService
     */
    @WebEndpoint(name = "NavigationServicePort")
    public NavigationWebService getNavigationServicePort() {
        return super.getPort(NavigationServicePort, NavigationWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns NavigationWebService
     */
    @WebEndpoint(name = "NavigationServicePort")
    public NavigationWebService getNavigationServicePort(WebServiceFeature... features) {
        return super.getPort(NavigationServicePort, NavigationWebService.class, features);
    }

}
