package gzrd.wsclient.navigation;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:40:32.246+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "NavigationWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface NavigationWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMenusNavigationByPosId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.navigation.GetMenusNavigationByPosId")
    @WebMethod
    @ResponseWrapper(localName = "getMenusNavigationByPosIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.navigation.GetMenusNavigationByPosIdResponse")
    public String getMenusNavigationByPosId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );
}
