package gzrd.wsclient.user;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:45:19.144+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "UserWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface UserWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getGroupCommonUsers", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetGroupCommonUsers")
    @WebMethod
    @ResponseWrapper(localName = "getGroupCommonUsersResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetGroupCommonUsersResponse")
    public java.util.List<User> getGroupCommonUsers(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            Long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByName")
    @WebMethod
    @ResponseWrapper(localName = "getUserByNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByNameResponse")
    public User getUserByName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByLoginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByLoginName")
    @WebMethod
    @ResponseWrapper(localName = "getUserByLoginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByLoginNameResponse")
    public String getUserByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByOrgId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUsersByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByOrgIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUsersByOrgIdResponse")
    public java.util.List<User> getUsersByOrgId(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllUserOnPos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetAllUserOnPos")
    @WebMethod
    @ResponseWrapper(localName = "getAllUserOnPosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetAllUserOnPosResponse")
    public java.util.List<User> getAllUserOnPos();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFavoriteUser", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetFavoriteUser")
    @WebMethod
    @ResponseWrapper(localName = "getFavoriteUserResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetFavoriteUserResponse")
    public java.util.List<FavoriteUser> getFavoriteUser(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            Long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "isCheckedMobile", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.IsCheckedMobile")
    @WebMethod
    @ResponseWrapper(localName = "isCheckedMobileResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.IsCheckedMobileResponse")
    public boolean isCheckedMobile(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMobileByLoginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetMobileByLoginName")
    @WebMethod
    @ResponseWrapper(localName = "getMobileByLoginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetMobileByLoginNameResponse")
    public String getMobileByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserIdsByRoleId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserIdsByRoleId")
    @WebMethod
    @ResponseWrapper(localName = "getUserIdsByRoleIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserIdsByRoleIdResponse")
    public java.util.List<Long> getUserIdsByRoleId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllUser", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetAllUser")
    @WebMethod
    @ResponseWrapper(localName = "getAllUserResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetAllUserResponse")
    public java.util.List<User> getAllUser();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getCityLeaders", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetCityLeaders")
    @WebMethod
    @ResponseWrapper(localName = "getCityLeadersResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetCityLeadersResponse")
    public java.util.List<UserDetailDTO> getCityLeaders();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserResponse")
    public User getUser(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateUserMobile", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.UpdateUserMobile")
    @WebMethod
    @ResponseWrapper(localName = "updateUserMobileResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.UpdateUserMobileResponse")
    public String updateUserMobile(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserChangeInfos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserChangeInfos")
    @WebMethod
    @ResponseWrapper(localName = "getUserChangeInfosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserChangeInfosResponse")
    public java.util.List<UpUserChangeForm> getUserChangeInfos(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByPosId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByPosId")
    @WebMethod
    @ResponseWrapper(localName = "getUserByPosIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByPosIdResponse")
    public User getUserByPosId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLeadersOfOrg", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLeadersOfOrg")
    @WebMethod
    @ResponseWrapper(localName = "getLeadersOfOrgResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLeadersOfOrgResponse")
    public java.util.List<SimpleUserDTO> getLeadersOfOrg(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserDetailDTO", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserDetailDTO")
    @WebMethod
    @ResponseWrapper(localName = "getUserDetailDTOResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserDetailDTOResponse")
    public UserDetailDTO getUserDetailDTO(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getManagerByOrgId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetManagerByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getManagerByOrgIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetManagerByOrgIdResponse")
    public String getManagerByOrgId(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserInfoByName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserInfoByName")
    @WebMethod
    @ResponseWrapper(localName = "getUserInfoByNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserInfoByNameResponse")
    public UserInfo getUserInfoByName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserJson", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserJson")
    @WebMethod
    @ResponseWrapper(localName = "getUserJsonResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserJsonResponse")
    public String getUserJson(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserIdsByFuncId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserIdsByFuncId")
    @WebMethod
    @ResponseWrapper(localName = "getUserIdsByFuncIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserIdsByFuncIdResponse")
    public java.util.List<Long> getUserIdsByFuncId(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUsersByLoginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.FindUsersByLoginName")
    @WebMethod
    @ResponseWrapper(localName = "findUsersByLoginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.FindUsersByLoginNameResponse")
    public String findUsersByLoginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLoginNameByMobileUserName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLoginNameByMobileUserName")
    @WebMethod
    @ResponseWrapper(localName = "getLoginNameByMobileUserNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLoginNameByMobileUserNameResponse")
    public String getLoginNameByMobileUserName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserByOrgIdAppIdRoleCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByOrgIdAppIdRoleCode")
    @WebMethod
    @ResponseWrapper(localName = "getUserByOrgIdAppIdRoleCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserByOrgIdAppIdRoleCodeResponse")
    public java.util.List<User> getUserByOrgIdAppIdRoleCode(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            Long arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserPassWordTow", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserPassWordTow")
    @WebMethod
    @ResponseWrapper(localName = "getUserPassWordTowResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserPassWordTowResponse")
    public String getUserPassWordTow(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUserInfo", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserInfo")
    @WebMethod
    @ResponseWrapper(localName = "getUserInfoResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUserInfoResponse")
    public UserInfo getUserInfo(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUsersByDeptId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUsersByDeptId")
    @WebMethod
    @ResponseWrapper(localName = "getUsersByDeptIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetUsersByDeptIdResponse")
    public java.util.List<User> getUsersByDeptId(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getLoginNameByEmail", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLoginNameByEmail")
    @WebMethod
    @ResponseWrapper(localName = "getLoginNameByEmailResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.GetLoginNameByEmailResponse")
    public String getLoginNameByEmail(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "findUsersByEmail", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.FindUsersByEmail")
    @WebMethod
    @ResponseWrapper(localName = "findUsersByEmailResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.user.FindUsersByEmailResponse")
    public String findUsersByEmail(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );
}
