package gzrd.wsclient.department;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:43:55.369+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "DeptWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface DeptWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptsByOrgId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptsByOrgId")
    @WebMethod
    @ResponseWrapper(localName = "getDeptsByOrgIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptsByOrgIdResponse")
    public java.util.List<Dept> getDeptsByOrgId(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptInfById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptInfById")
    @WebMethod
    @ResponseWrapper(localName = "getDeptInfByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptInfByIdResponse")
    public Deptment getDeptInfById(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "deptExists", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.DeptExists")
    @WebMethod
    @ResponseWrapper(localName = "deptExistsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.DeptExistsResponse")
    public Boolean deptExists(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptsForUser", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptsForUser")
    @WebMethod
    @ResponseWrapper(localName = "getDeptsForUserResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptsForUserResponse")
    public String getDeptsForUser(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateDeptFuncById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.UpdateDeptFuncById")
    @WebMethod
    @ResponseWrapper(localName = "updateDeptFuncByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.UpdateDeptFuncByIdResponse")
    public boolean updateDeptFuncById(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getDeptChangeInfos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptChangeInfos")
    @WebMethod
    @ResponseWrapper(localName = "getDeptChangeInfosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.department.GetDeptChangeInfosResponse")
    public java.util.List<UpDeptChangeForm> getDeptChangeInfos(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg1
    );
}
