package gzrd.wsclient.department;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:43:55.415+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "DeptWebService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/DeptWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class DeptWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "DeptWebService");
    public final static QName DeptWebServicePort = new QName("http://hugeinfo.com.cn", "DeptWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/DeptWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(DeptWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/DeptWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public DeptWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DeptWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DeptWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns DeptWebService
     */
    @WebEndpoint(name = "DeptWebServicePort")
    public DeptWebService getDeptWebServicePort() {
        return super.getPort(DeptWebServicePort, DeptWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DeptWebService
     */
    @WebEndpoint(name = "DeptWebServicePort")
    public DeptWebService getDeptWebServicePort(WebServiceFeature... features) {
        return super.getPort(DeptWebServicePort, DeptWebService.class, features);
    }

}
