package gzrd.wsclient.login;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:45:57.034+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "LoginWebService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/LoginWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class LoginWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "LoginWebService");
    public final static QName LoginWebServicePort = new QName("http://hugeinfo.com.cn", "LoginWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/LoginWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LoginWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/LoginWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LoginWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LoginWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LoginWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns LoginWebService
     */
    @WebEndpoint(name = "LoginWebServicePort")
    public LoginWebService getLoginWebServicePort() {
        return super.getPort(LoginWebServicePort, LoginWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LoginWebService
     */
    @WebEndpoint(name = "LoginWebServicePort")
    public LoginWebService getLoginWebServicePort(WebServiceFeature... features) {
        return super.getPort(LoginWebServicePort, LoginWebService.class, features);
    }

}
