package gzrd.wsclient.login;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:45:56.983+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "LoginWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface LoginWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "UserFuncValid", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.UserFuncValid")
    @WebMethod(operationName = "UserFuncValid")
    @ResponseWrapper(localName = "UserFuncValidResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.UserFuncValidResponse")
    public String userFuncValid(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            long arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loginCheckValid", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.LoginCheckValid")
    @WebMethod
    @ResponseWrapper(localName = "loginCheckValidResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.LoginCheckValidResponse")
    public String loginCheckValid(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "loginCheckValidBolean", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.LoginCheckValidBolean")
    @WebMethod
    @ResponseWrapper(localName = "loginCheckValidBoleanResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.LoginCheckValidBoleanResponse")
    public boolean loginCheckValidBolean(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "validateUser", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.ValidateUser")
    @WebMethod
    @ResponseWrapper(localName = "validateUserResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.ValidateUserResponse")
    public Boolean validateUser(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updatePwd", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.UpdatePwd")
    @WebMethod
    @ResponseWrapper(localName = "updatePwdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.UpdatePwdResponse")
    public boolean updatePwd(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
            String arg4
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getFuncsByLonginName", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.GetFuncsByLonginName")
    @WebMethod
    @ResponseWrapper(localName = "getFuncsByLonginNameResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.login.GetFuncsByLonginNameResponse")
    public java.util.List<UpFunctionForm> getFuncsByLonginName(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );
}
