package gzrd.wsclient.unit;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:42:11.160+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "OrgWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface OrgWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "treegetAllChildOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllChildOrgs")
    @WebMethod
    @ResponseWrapper(localName = "treegetAllChildOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllChildOrgsResponse")
    public java.util.List<Org> treegetAllChildOrgs(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "updateOrgById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.UpdateOrgById")
    @WebMethod
    @ResponseWrapper(localName = "updateOrgByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.UpdateOrgByIdResponse")
    public boolean updateOrgById(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            String arg1,
            @WebParam(name = "arg2", targetNamespace = "")
            String arg2,
            @WebParam(name = "arg3", targetNamespace = "")
            String arg3,
            @WebParam(name = "arg4", targetNamespace = "")
            String arg4,
            @WebParam(name = "arg5", targetNamespace = "")
            long arg5,
            @WebParam(name = "arg6", targetNamespace = "")
            long arg6,
            @WebParam(name = "arg7", targetNamespace = "")
            String arg7
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgWithChildOrgsCascade", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgWithChildOrgsCascade")
    @WebMethod
    @ResponseWrapper(localName = "getOrgWithChildOrgsCascadeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgWithChildOrgsCascadeResponse")
    public Org getOrgWithChildOrgsCascade(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAreaSortDTOList", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAreaSortDTOList")
    @WebMethod
    @ResponseWrapper(localName = "getAreaSortDTOListResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAreaSortDTOListResponse")
    public java.util.List<AreaOrg> getAreaSortDTOList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgById")
    @WebMethod
    @ResponseWrapper(localName = "getOrgByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgByIdResponse")
    public Org getOrgById(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgWithChildOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgWithChildOrgs")
    @WebMethod
    @ResponseWrapper(localName = "getOrgWithChildOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgWithChildOrgsResponse")
    public java.util.List<Org> getOrgWithChildOrgs(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getMainOrg", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetMainOrg")
    @WebMethod
    @ResponseWrapper(localName = "getMainOrgResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetMainOrgResponse")
    public Org getMainOrg(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgsByUnitType", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgsByUnitType")
    @WebMethod
    @ResponseWrapper(localName = "getOrgsByUnitTypeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgsByUnitTypeResponse")
    public java.util.List<Org> getOrgsByUnitType(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllSortCascadeTopOrg", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllSortCascadeTopOrg")
    @WebMethod
    @ResponseWrapper(localName = "getAllSortCascadeTopOrgResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllSortCascadeTopOrgResponse")
    public java.util.List<Sort> getAllSortCascadeTopOrg();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgDtoListByRoleId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgDtoListByRoleId")
    @WebMethod
    @ResponseWrapper(localName = "getOrgDtoListByRoleIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgDtoListByRoleIdResponse")
    public java.util.List<String> getOrgDtoListByRoleId(
            @WebParam(name = "arg0", targetNamespace = "")
            Long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "treegetAllChildOrgsCascade", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllChildOrgsCascade")
    @WebMethod
    @ResponseWrapper(localName = "treegetAllChildOrgsCascadeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllChildOrgsCascadeResponse")
    public java.util.List<Org> treegetAllChildOrgsCascade(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "treegetOrgWithAllChildOrgsCascade", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetOrgWithAllChildOrgsCascade")
    @WebMethod
    @ResponseWrapper(localName = "treegetOrgWithAllChildOrgsCascadeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetOrgWithAllChildOrgsCascadeResponse")
    public Org treegetOrgWithAllChildOrgsCascade(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllTopOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllTopOrgs")
    @WebMethod
    @ResponseWrapper(localName = "getAllTopOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllTopOrgsResponse")
    public java.util.List<Org> getAllTopOrgs();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAreaSortDTOListOfAreaIds", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAreaSortDTOListOfAreaIds")
    @WebMethod
    @ResponseWrapper(localName = "getAreaSortDTOListOfAreaIdsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAreaSortDTOListOfAreaIdsResponse")
    public java.util.List<AreaOrg> getAreaSortDTOListOfAreaIds(
            @WebParam(name = "arg0", targetNamespace = "")
            String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgChangeInfos", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgChangeInfos")
    @WebMethod
    @ResponseWrapper(localName = "getOrgChangeInfosResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgChangeInfosResponse")
    public java.util.List<UpOrgChangeForm> getOrgChangeInfos(
            @WebParam(name = "arg0", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg0,
            @WebParam(name = "arg1", targetNamespace = "")
            javax.xml.datatype.XMLGregorianCalendar arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getSimpleOrgList", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetSimpleOrgList")
    @WebMethod
    @ResponseWrapper(localName = "getSimpleOrgListResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetSimpleOrgListResponse")
    public java.util.List<SimpleOrgDTO> getSimpleOrgList();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getChildOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetChildOrgs")
    @WebMethod
    @ResponseWrapper(localName = "getChildOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetChildOrgsResponse")
    public java.util.List<Org> getChildOrgs(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "treegetAllOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllOrgs")
    @WebMethod
    @ResponseWrapper(localName = "treegetAllOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetAllOrgsResponse")
    public java.util.List<Org> treegetAllOrgs();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "treegetOrgWithAllChildOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetOrgWithAllChildOrgs")
    @WebMethod
    @ResponseWrapper(localName = "treegetOrgWithAllChildOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.TreegetOrgWithAllChildOrgsResponse")
    public Org treegetOrgWithAllChildOrgs(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgIsPub", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgIsPub")
    @WebMethod
    @ResponseWrapper(localName = "getOrgIsPubResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgIsPubResponse")
    public Org getOrgIsPub(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllChildOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllChildOrgs")
    @WebMethod
    @ResponseWrapper(localName = "getAllChildOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllChildOrgsResponse")
    public java.util.List<Org> getAllChildOrgs(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllOrgs", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllOrgs")
    @WebMethod
    @ResponseWrapper(localName = "getAllOrgsResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetAllOrgsResponse")
    public java.util.List<Org> getAllOrgs();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getOrgByIdCascade", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgByIdCascade")
    @WebMethod
    @ResponseWrapper(localName = "getOrgByIdCascadeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.unit.GetOrgByIdCascadeResponse")
    public Org getOrgByIdCascade(
            @WebParam(name = "arg0", targetNamespace = "")
            long arg0
    );
}
