package gzrd.wsclient.unit;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.13
 * 2015-02-06T15:42:11.220+08:00
 * Generated source version: 2.7.13
 * 
 */
@WebServiceClient(name = "OrgWebService", 
                  wsdlLocation = "http://192.168.0.150:8080/rdup/ws/OrgWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class OrgWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "OrgWebService");
    public final static QName OrgWebServicePort = new QName("http://hugeinfo.com.cn", "OrgWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://192.168.0.150:8080/rdup/ws/OrgWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(OrgWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://192.168.0.150:8080/rdup/ws/OrgWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public OrgWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OrgWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OrgWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns OrgWebService
     */
    @WebEndpoint(name = "OrgWebServicePort")
    public OrgWebService getOrgWebServicePort() {
        return super.getPort(OrgWebServicePort, OrgWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns OrgWebService
     */
    @WebEndpoint(name = "OrgWebServicePort")
    public OrgWebService getOrgWebServicePort(WebServiceFeature... features) {
        return super.getPort(OrgWebServicePort, OrgWebService.class, features);
    }

}
