package gzrd.wsclient.role;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2014-11-25T14:21:46.970+08:00
 * Generated source version: 2.6.9
 * 
 */
@WebServiceClient(name = "RoleWebService", 
                  wsdlLocation = "http://cas.rd.gz.cn/rdup/ws/RoleWebService?wsdl",
                  targetNamespace = "http://hugeinfo.com.cn") 
public class RoleWebService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://hugeinfo.com.cn", "RoleWebService");
    public final static QName RoleWebServicePort = new QName("http://hugeinfo.com.cn", "RoleWebServicePort");
    static {
        URL url = null;
        try {
            url = new URL("http://cas.rd.gz.cn/rdup/ws/RoleWebService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RoleWebService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://cas.rd.gz.cn/rdup/ws/RoleWebService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RoleWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RoleWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleWebService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns RoleWebService
     */
    @WebEndpoint(name = "RoleWebServicePort")
    public RoleWebService getRoleWebServicePort() {
        return super.getPort(RoleWebServicePort, RoleWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RoleWebService
     */
    @WebEndpoint(name = "RoleWebServicePort")
    public RoleWebService getRoleWebServicePort(WebServiceFeature... features) {
        return super.getPort(RoleWebServicePort, RoleWebService.class, features);
    }

}
