package gzrd.wsclient.role;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.9
 * 2014-11-25T14:21:46.920+08:00
 * Generated source version: 2.6.9
 * 
 */
@WebService(targetNamespace = "http://hugeinfo.com.cn", name = "RoleWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface RoleWebService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRolesByPosIdAndAppCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByPosIdAndAppCode")
    @WebMethod
    @ResponseWrapper(localName = "getRolesByPosIdAndAppCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByPosIdAndAppCodeResponse")
    public java.util.List<gzrd.wsclient.role.Role> getRolesByPosIdAndAppCode(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllRoles", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetAllRoles")
    @WebMethod
    @ResponseWrapper(localName = "getAllRolesResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetAllRolesResponse")
    public java.util.List<gzrd.wsclient.role.Role> getAllRoles();

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRolesByAppCode", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByAppCode")
    @WebMethod
    @ResponseWrapper(localName = "getRolesByAppCodeResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByAppCodeResponse")
    public java.util.List<gzrd.wsclient.role.Role> getRolesByAppCode(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleIdsByFuncId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRoleIdsByFuncId")
    @WebMethod
    @ResponseWrapper(localName = "getRoleIdsByFuncIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRoleIdsByFuncIdResponse")
    public java.util.List<java.lang.Long> getRoleIdsByFuncId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRoleById", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRoleById")
    @WebMethod
    @ResponseWrapper(localName = "getRoleByIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRoleByIdResponse")
    public gzrd.wsclient.role.Role getRoleById(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRolesByUserId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByUserId")
    @WebMethod
    @ResponseWrapper(localName = "getRolesByUserIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByUserIdResponse")
    public java.util.List<gzrd.wsclient.role.Role> getRolesByUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAllRoleIdsByUserId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetAllRoleIdsByUserId")
    @WebMethod
    @ResponseWrapper(localName = "getAllRoleIdsByUserIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetAllRoleIdsByUserIdResponse")
    public java.util.List<java.lang.Long> getAllRoleIdsByUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getRolesByPosId", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByPosId")
    @WebMethod
    @ResponseWrapper(localName = "getRolesByPosIdResponse", targetNamespace = "http://hugeinfo.com.cn", className = "gzrd.wsclient.role.GetRolesByPosIdResponse")
    public java.util.List<gzrd.wsclient.role.Role> getRolesByPosId(
        @WebParam(name = "arg0", targetNamespace = "")
        long arg0
    );
}
