package com.lefthand.base.comm;

/**
 * 错误类型
 * Created by hp on 2015/6/15.
 */
public enum BaseErrorEnum {
    ERR_DAO_RODO_INSERT,
    ERR_DAO_RODO_INSERTBATCH,
    ERR_DAO_RODO_UPDATE,
    ERR_DAO_RODO_UPDATEMAP,
    ERR_DAO_RODO_DELETEBYKEY,
    ERR_DAO_RODO_DELETE,
    ERR_DAO_RODO_DELETEBATCH,
    ERR_DAO_RODO_FETCH,
    ERR_DAO_RODO_COUNT,
    ERR_DAO_RODO_LIST,
    ERR_DAO_RODO_PAGE
}
